[app]
    host            = "127.0.0.1:8003"

[configDB]
    host            = "127.0.0.1"
    port            = 5432
    user            = "postgres"
    password        = "password"
    dbname          = "go-postgres"
